(defun convert-to-binary (n)
  (if (= n 0)
        (list 0)
        (if (= n 1) 
            (list 1)
            (nconc (convert-to-binary (floor n 2)) (list (mod n 2)))
        )
    )
)

(defun ConvertToBinaryTest () 
"Testowanie Konwersji z Systemu Dziesiętnego na binarny"
	(check (= (convert-to-binary 5) `(1 0 1)))
	(check (= (convert-to-binary 31) `(1 1 1 1 1)))
	(check (= (convert-to-binary 32) `(1 1 1 1 1 0)))
)